version: '3.4'

services:
  hero.server:
    image: ${DOCKER_REGISTRY-}heroserver
    build:
      context: .
      dockerfile: Hero.Server/Dockerfile
    environment:
      - ConnectionStrings__Default=${ConnectionStrings__Default}
      - Services__Keycloak__Username=${Services__Keycloak__Username}
      - Services__Keycloak__Password=${Services__Keycloak__Password}
