version: '3.4'

services:
  hero.server:
    image: ${DOCKER_REGISTRY-}heroserver
    ports:
      - 443:443
      - 80:80
    build:
      context: .
      dockerfile: Hero.Server/Dockerfile
      - C:\Users\mail\Documents\kalinar-app-firebase-adminsdk-86tpz-ac8bb876ea.json:/resources/credentials.json
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/resources/credentials.json
      - ConnectionStrings__Default=${ConnectionStrings__Default}
      - Services__Keycloak__Username=${Services__Keycloak__Username}
      - Services__Keycloak__Password=${Services__Keycloak__Password}
