name: Build and Publish Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
 IMAGE_NAME: server

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Build and push Docker images
      uses: docker/build-push-action@v3.1.1
      with:
        file: Hero.Server/Dockerfile
        push: true
        tags: $IMAGE_NAME:latest
        github-token:  ${{ github.token }}

      
